### PR TITLE
MNT: Adjust to changes in intake

### PR DESCRIPTION
**Pull request by tacaswell**
This is the location of `RemoteCatalog` on the default branch of intake, I suspect it is better to shim it here and make sure the deprecation is noted in intake.

### CODE REVIEW

**Review by danielballan — APPROVED** [review]
Thanks. Been meaning to get around to this. Our "canary" (CI build against intake `master`) has been singing for some time.

**Comment by danielballan** [comment]
Passes tests against intake `master` (currently 51b1a183) and intake `0.6.0` locally.

**Review by danielballan — CHANGES_REQUESTED** [review]
Docs do not build without errors. There is more work to be done to cope with this change in intake:

https://github.com/intake/intake/commit/4aa561c86503d609ed73a5ae9c7e9256b6560bb4#diff-4e371ca3c37982987024b768df161ca8c8da696ff4a3459035c122e6cfb9bd15R406-R408

**Comment by danielballan** [comment]
56e1897 is either wrong or incomplete.

**Comment by danielballan** [comment]
Reported upstream, as linked above.

**Review by danielballan — APPROVED** [review]
Looking better now.

**Review by dylanmcreynolds — APPROVED** [review]

**Pull request merged**
