### PR TITLE
Add replay script

### PR DESCRIPTION
**Pull request by AbbyGi**
## Description

Adds a script that replays Bluesky runs with the correct timing.

## Motivation and Context

This simulates live streaming data so we can develop and test code for streaming data without needing to be at a beamline looking at new data.

## How Has This Been Tested?

This has been tested interactively while developing GUI applications.

### CODE REVIEW

**Comment by gwbischof** [comment]
How are Kafka and ZMQ used here?

**Comment by gwbischof** [comment]
Could `replay` take a list of generators? So I can simulate multiple runs from different beamlines at the same time? Or maybe we should make a new function that replays multiple generators?

**Comment by tacaswell** [comment]
You probably want to lift the time sorting logic than merges documents from multiple collections into a time ordered stream in databroker and write a function like

```python
def merge_runs(*runs):
    for name, doc in sort_and_collate(runs):
        yield name, doc
```

**Comment by gwbischof** [comment]
There is this function here that does something like that: https://github.com/bluesky/databroker/blob/970e9148dfab5e77101d40f059ecb30d064eac81/databroker/core.py#L436

Which reminds me, that we may need to interlace the event/datum_pages for a single run if we want them to be in the right order. But if the generator is canonical() then that should already be done.

**Comment by danielballan** [comment]
> How are Kafka and ZMQ used here?

The CLI portion of this (in `main()`) is designed to replay the documents over the network, via 0MQ or Kafka, so that can be consumed by some other process. The underlying function with the "brains" (`replay`) can also be used directly in process, without a CLI or network, if that's better for your use case.

> Could replay take a list of generators? So I can simulate multiple runs from different beamlines at the same time? 

I see a way to do this that is simpler and also more realistic: a separate process per beamline, each running `replay` on one run at a time, and each (naturally) making reference to the same clock. With a Run, there are strict ordering guarantees, but across beamlines, there is a little more slip in the order of things, and the relative timing does not have to be exactly perfect. Assuming your goal is load-testing Mongo, hitting it with ~28 processes all writing concurrently is more realistic that funneling everything through one process.

> Which reminds me, that we may need to interlace the event/datum_pages for a single run if we want them to be in the right order. But if the generator is canonical() then that should already be done.

This now happens here. It turns out it's a lot simpler to do this at the single-document level --- straight from Mongo before anythign could have been grouped into pages.

https://github.com/bluesky/databroker/blob/c1f67cfd2a6e882ad0879c97a14a3dca6b76185b/databroker/mongo_normalized.py#L327-L381

Replay can count on the documents coming out of databroker in strict time order.

**Comment by mrakitin** [comment]
Is this PR relevant to these items?
- https://github.com/bluesky/event-model/issues/150
- https://github.com/bluesky/event-model/pull/155
- https://github.com/bluesky/event-model/issues/156

**Comment by danielballan** [comment]
Certainly relevant to https://github.com/bluesky/event-model/issues/150 and https://github.com/bluesky/event-model/pull/155. We may need to think about how something in event-model itself (or bluesky-live?) would be useful, in addition to this tool in databroker. Probably not? Needs though.

**Pull request merged**
