### PR TITLE
index.html

### PR DESCRIPTION
**Pull request by Mihir008**
It is a portfolio website created using html and css.

### CODE REVIEW

**Comment by Mihir008** [comment]
It is a portfolio website created using html and css.

**Comment by Mihir008** [comment]
It is a portfolio website created using html and css.

**Comment by danielballan** [comment]
This is malicious spam.

**Comment by mrakitin** [comment]
We see this type of PRs during the hacktoberfest...

**Comment by mrakitin** [comment]
https://github.com/bluesky/bluesky.github.io/pull/18 - similar thing + deleted account. We probably should remove the labels to avoid this type of spam.

**Comment by mrakitin** [comment]
And GitHub gives "stars" for that!
image

**Comment by danielballan** [comment]
Good call.

**Pull request closed without merging**
