### PR TITLE
interlace fix

### PR DESCRIPTION
**Pull request by gwbischof**
Fixes https://github.com/bluesky/databroker/issues/520

### CODE REVIEW

**Comment by tacaswell** [comment]
I think the `uid` should go before the indx as the `uid` is something from the data where as the index is a internal thing that only needs to be there so we can push the next element from the generator into the heap.

**Comment by tacaswell** [comment]
I don't think `interlace_event_page_chunks` actually works as intended.  It comes out ordered (so the tests pass), but many too few chunks get emitted.  I pushed a test that used to fail and simplified `interlace_event_page_chunks` to use `interlace_event_pages` internally.

**Comment by gwbischof** [comment]
> I don't think `interlace_event_page_chunks` actually works as intended. It comes out ordered (so the tests pass), but many too few chunks get emitted. I pushed a test that used to fail and simplified `interlace_event_page_chunks` to use `interlace_event_pages` internally.

Nice simplification and update to the test! Your updated test is passing locally.

**Comment by danielballan** [comment]
Note this PR targeted the wrong branch (fortunately, a disposable one, not a persistent back-port branch or anything like that). See #521 for the intended PR into `master`.

**Pull request merged**
