### PR TITLE
Use a more robust ALL sentinel.

### PR DESCRIPTION
**Pull request by danielballan**
Needs a Tiled release xref https://github.com/bluesky/tiled/pull/421

### CODE REVIEW

**Review by tacaswell — APPROVED** [review]
pending turning the crank on tiled.

**Comment by danielballan** [comment]
The necessary change to Tiled has been released in v0.1.0a86, and I have updated the minimum version pin here.

**Comment by tacaswell** [comment]
We might want to pin setuptools back to avoid the namespace package issue: https://github.com/pypa/setuptools/pull/3434

**Comment by danielballan** [comment]
Hmm. If we handle that in event-model that might settle the issue for all relevant repos.

**Pull request merged**
