### PR TITLE
FIX: do not error our when checking comparison with non-Header

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by danielballan** [comment]
Power-cycled to run against new GitHub Actions CI.

**Review by danielballan — CHANGES_REQUESTED** [review]
Good idea. Test failures look real.

**Comment by danielballan** [comment]
Found the issue, fixed it for you.

**Review by danielballan — APPROVED** [review]

**Comment by tacaswell** [comment]
Thanks!

**Pull request merged**
