### PR TITLE
be kinder about checking data keys and be kinder about yaml usage

### PR DESCRIPTION
**Pull request by CJ-Wright**
Just in case one doesn't have the newest yaml installed or somehow the data_keys and event data keys don't match

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@bluesky/maintainers I think this is ready for review. (test failures are either sphinx issues or server timeouts)

**Comment by danielballan** [comment]
I think the YAML stuff is good to merge, but the data keys stuff is a very different issue and probably requires more thought. If you want to get the YAML in soon, a separate PR would help.

**Comment by CJ-Wright** [comment]
Hmm ok. I have run into the data key stuff in production at PDF (see the 'PDF' databroker `1f529bb6-3a66-45d3-a122-37362b9ce82c`)

**Comment by danielballan** [comment]
We should make validation stricter in order to catch that and then we should fix the broken EventDescriptors in the database.

**Pull request closed without merging**
