### PR TITLE
Nice yaml handling

### PR DESCRIPTION
**Pull request by CJ-Wright**
Closes #411

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@bluesky/maintainers ready for review!

**Comment by danielballan** [comment]
Fixed a dependency issue in 34cb75d, and now the tests pass (modulo the occasional "server startup timeout", which is a known issue).

Now I get this error when the docs build:

```
don't know which module to import for autodocumenting 'event_sources_by_name' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
```

https://travis-ci.org/bluesky/databroker/jobs/541963561#L1436

I cannot reproduce that locally.

**Comment by danielballan** [comment]
@ke-zhang-rd We also already have `.. currentmodule` set here https://github.com/bluesky/databroker/pull/413/commits/1554e8e76c07e117f941b7edeeeac97261173403#diff-7ac7fec400c200ba5a183ddde06a7889R13

**Comment by danielballan** [comment]
OK, so the issues were:

1. Pip sees that databroker needs `attrs` and then _later_ sees that `jsonschema` needs `attrs >=17.4.0`, but apparently it says, "Oh, I already know about needing `attrs`," and it _ignores the pin_. The workaround is to pin `attrs >=17.4.0` in databroker as well.
2. Sphinx released `2.1.0`, which has a bug that breaks out documentation build. I can now reproduce it locally. Building with `2.0.1` (the previous release) works fine. I have banned `2.1.0`, and I am about to report the issue upstream to sphinx in the hope it will be fixed in `2.1.1`.

**Comment by danielballan** [comment]
2/3 builds passed, and 1 had a single "Server startup timeout error". Merging.

**Comment by danielballan** [comment]
Upstream bug report: https://github.com/sphinx-doc/sphinx/issues/6452

**Pull request merged**
