### PR TITLE
Add SCHRAM-SHA authorization support and correct FileStore handlers i…

### PR DESCRIPTION
**Pull request by ARamirezHong**
…mport.

### CODE REVIEW

**Comment by danielballan** [comment]
Thanks for the contribution, @ARamirezHong! @arkilic will take a look at this shortly.

**Comment by tacaswell** [comment]
@ARamirezHong Sorry this has sat so long without attention!

While you are touching this can you also move `auth` into the config dictionary?

**Comment by danielballan** [comment]
@ARamirezHong Is this still a going concern?

**Comment by danielballan** [comment]
Please reopen if this is a going concern.

**Pull request closed without merging**
